version: '3'
services:
  mysql:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: Root.
      MYSQL_DATABASE: shopping-cart
    volumes:
      - ./databases/mysql_query.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    container_name: app_sec-mysql-1
  tomcat:
    image: tomcat:8.5.94
    ports:
      - "8080:8080"
    volumes:
      - ./target/shopping-cart-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/shopping-cart.war
    depends_on:
      - mysql
    command: catalina.sh run

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - tomcat


